In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd '/content/drive/MyDrive/Projects/Harry Potter GPT'

/content/drive/MyDrive/Projects/Harry Potter GPT


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# read it in to inspect it
with open('HarryPotter_SorcererStone.txt', 'r', encoding='utf-8') as f:
    part1 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Chamber of Secrets.txt', 'r', encoding='utf-8') as f:
    part2 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Prisoner of Azkaban .txt', 'r', encoding='utf-8') as f:
    part3 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Prisoner of Azkaban .txt', 'r', encoding='utf-8') as f:
    part3 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Goblet of Fire.txt', 'r', encoding='utf-8') as f:
    part4 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Order of the Phoenix.txt', 'r', encoding='utf-8') as f:
    part5 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and The Half-Blood Prince.txt', 'r', encoding='utf-8') as f:
    part6 = f.read()

In [ ]:
# read it in to inspect it
with open('Harry Potter and the Deathly Hallows .txt', 'r', encoding='utf-8') as f:
    part7 = f.read()

In [ ]:
# combine all the files together
text = part1 + part2 + part3 +part4 + part5 + part6 + part7

In [ ]:
print("Length of dataset in characters: ", len(text))

Length of dataset in characters:  6340988


In [ ]:
# First 1000 characters of the dataset
print(text[:1000])

Harry Potter and the Sorcerer's Stone
CHAPTER ONE
THE BOY WHO LIVED
Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense.
Mr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.
The Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn't think they could bear it if anyone found out about the Potters. Mrs. Pot

In [ ]:
# Get all the characters in the entire dataset in a sorted mannner
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"$%&'()*,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz|}~é–—‘’“”…　【】下为书件作你做全制区坛子式志您文新最本来格电的社立米糯自要论载
137


In [ ]:
type(chars)

list

In [ ]:
import string

# Define a set of valid characters (alphabets, numerals, and special characters)
valid_characters = set(string.ascii_letters + string.digits + string.punctuation )

# Filter out non-valid characters
chars = [char for char in chars if char in valid_characters]

# Join the filtered characters back into a string
# filtered_string = ''.join(filtered_characters)
chars.extend(' ')

print(chars)

['!', '"', '$', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}', '~', ' ']


In [ ]:
# checking if all the elements in the list are unique or not
unique_set = set(chars)
if len(chars)==len(unique_set):
  print("equal")
else:
  print('no')

equal


In [ ]:
# Create a mapping from characters to integers
# string to integer mapping
stoi = {ch: i for i, ch in enumerate(chars)}
print(stoi)

{'!': 0, '"': 1, '$': 2, '%': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '/': 12, '0': 13, '1': 14, '2': 15, '3': 16, '4': 17, '5': 18, '6': 19, '7': 20, '8': 21, '9': 22, ':': 23, ';': 24, '<': 25, '=': 26, '>': 27, '?': 28, 'A': 29, 'B': 30, 'C': 31, 'D': 32, 'E': 33, 'F': 34, 'G': 35, 'H': 36, 'I': 37, 'J': 38, 'K': 39, 'L': 40, 'M': 41, 'N': 42, 'O': 43, 'P': 44, 'Q': 45, 'R': 46, 'S': 47, 'T': 48, 'U': 49, 'V': 50, 'W': 51, 'X': 52, 'Y': 53, 'Z': 54, '[': 55, '\\': 56, ']': 57, '^': 58, '_': 59, '`': 60, 'a': 61, 'b': 62, 'c': 63, 'd': 64, 'e': 65, 'f': 66, 'g': 67, 'h': 68, 'i': 69, 'j': 70, 'k': 71, 'l': 72, 'm': 73, 'n': 74, 'o': 75, 'p': 76, 'q': 77, 'r': 78, 's': 79, 't': 80, 'u': 81, 'v': 82, 'w': 83, 'x': 84, 'y': 85, 'z': 86, '|': 87, '}': 88, '~': 89, ' ': 90}


In [ ]:
stoi['\n'] = 91
print(stoi)

{'!': 0, '"': 1, '$': 2, '%': 3, '&': 4, "'": 5, '(': 6, ')': 7, '*': 8, ',': 9, '-': 10, '.': 11, '/': 12, '0': 13, '1': 14, '2': 15, '3': 16, '4': 17, '5': 18, '6': 19, '7': 20, '8': 21, '9': 22, ':': 23, ';': 24, '<': 25, '=': 26, '>': 27, '?': 28, 'A': 29, 'B': 30, 'C': 31, 'D': 32, 'E': 33, 'F': 34, 'G': 35, 'H': 36, 'I': 37, 'J': 38, 'K': 39, 'L': 40, 'M': 41, 'N': 42, 'O': 43, 'P': 44, 'Q': 45, 'R': 46, 'S': 47, 'T': 48, 'U': 49, 'V': 50, 'W': 51, 'X': 52, 'Y': 53, 'Z': 54, '[': 55, '\\': 56, ']': 57, '^': 58, '_': 59, '`': 60, 'a': 61, 'b': 62, 'c': 63, 'd': 64, 'e': 65, 'f': 66, 'g': 67, 'h': 68, 'i': 69, 'j': 70, 'k': 71, 'l': 72, 'm': 73, 'n': 74, 'o': 75, 'p': 76, 'q': 77, 'r': 78, 's': 79, 't': 80, 'u': 81, 'v': 82, 'w': 83, 'x': 84, 'y': 85, 'z': 86, '|': 87, '}': 88, '~': 89, ' ': 90, '\n': 91}


In [ ]:
# integer to string mapping
itos = {i: ch for i,ch in enumerate(chars)}
print(itos)

{0: '!', 1: '"', 2: '$', 3: '%', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '/', 13: '0', 14: '1', 15: '2', 16: '3', 17: '4', 18: '5', 19: '6', 20: '7', 21: '8', 22: '9', 23: ':', 24: ';', 25: '<', 26: '=', 27: '>', 28: '?', 29: 'A', 30: 'B', 31: 'C', 32: 'D', 33: 'E', 34: 'F', 35: 'G', 36: 'H', 37: 'I', 38: 'J', 39: 'K', 40: 'L', 41: 'M', 42: 'N', 43: 'O', 44: 'P', 45: 'Q', 46: 'R', 47: 'S', 48: 'T', 49: 'U', 50: 'V', 51: 'W', 52: 'X', 53: 'Y', 54: 'Z', 55: '[', 56: '\\', 57: ']', 58: '^', 59: '_', 60: '`', 61: 'a', 62: 'b', 63: 'c', 64: 'd', 65: 'e', 66: 'f', 67: 'g', 68: 'h', 69: 'i', 70: 'j', 71: 'k', 72: 'l', 73: 'm', 74: 'n', 75: 'o', 76: 'p', 77: 'q', 78: 'r', 79: 's', 80: 't', 81: 'u', 82: 'v', 83: 'w', 84: 'x', 85: 'y', 86: 'z', 87: '|', 88: '}', 89: '~', 90: ' '}


In [ ]:
itos[91] = '\n'

In [ ]:
print(itos)

{0: '!', 1: '"', 2: '$', 3: '%', 4: '&', 5: "'", 6: '(', 7: ')', 8: '*', 9: ',', 10: '-', 11: '.', 12: '/', 13: '0', 14: '1', 15: '2', 16: '3', 17: '4', 18: '5', 19: '6', 20: '7', 21: '8', 22: '9', 23: ':', 24: ';', 25: '<', 26: '=', 27: '>', 28: '?', 29: 'A', 30: 'B', 31: 'C', 32: 'D', 33: 'E', 34: 'F', 35: 'G', 36: 'H', 37: 'I', 38: 'J', 39: 'K', 40: 'L', 41: 'M', 42: 'N', 43: 'O', 44: 'P', 45: 'Q', 46: 'R', 47: 'S', 48: 'T', 49: 'U', 50: 'V', 51: 'W', 52: 'X', 53: 'Y', 54: 'Z', 55: '[', 56: '\\', 57: ']', 58: '^', 59: '_', 60: '`', 61: 'a', 62: 'b', 63: 'c', 64: 'd', 65: 'e', 66: 'f', 67: 'g', 68: 'h', 69: 'i', 70: 'j', 71: 'k', 72: 'l', 73: 'm', 74: 'n', 75: 'o', 76: 'p', 77: 'q', 78: 'r', 79: 's', 80: 't', 81: 'u', 82: 'v', 83: 'w', 84: 'x', 85: 'y', 86: 'z', 87: '|', 88: '}', 89: '~', 90: ' ', 91: '\n'}


In [ ]:
# encode = lambda s: [stoi[c] for c in s]  # Encoder: take a string, output a list of integers
encode = lambda s: [stoi.get(c, 100) for c in s]  # Encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos.get(i, '<unk>') for i in l])  # Decoder: take a list of integers, output a string

# decode = lambda l: ''.join([itos[i] for i in l])  # Decoder: take a list of integers, output a string

In [ ]:
# Test the encoding and decoding
print(encode("Harry Potter and the Sorcerer's Stone"))
print(decode(encode("Harry Potter and the Sorcerer's Stone")))

[36, 61, 78, 78, 85, 90, 44, 75, 80, 80, 65, 78, 90, 61, 74, 64, 90, 80, 68, 65, 90, 47, 75, 78, 63, 65, 78, 65, 78, 5, 79, 90, 47, 80, 75, 74, 65]
Harry Potter and the Sorcerer's Stone


In [ ]:
import torch
data = torch.tensor(encode(text), dtype = torch.long)
print(data.shape, data.type)
print(data[:1000])

torch.Size([6340988]) <built-in method type of Tensor object at 0x7b887bc26250>
tensor([36, 61, 78, 78, 85, 90, 44, 75, 80, 80, 65, 78, 90, 61, 74, 64, 90, 80,
        68, 65, 90, 47, 75, 78, 63, 65, 78, 65, 78,  5, 79, 90, 47, 80, 75, 74,
        65, 91, 31, 36, 29, 44, 48, 33, 46, 90, 43, 42, 33, 91, 48, 36, 33, 90,
        30, 43, 53, 90, 51, 36, 43, 90, 40, 37, 50, 33, 32, 91, 41, 78, 11, 90,
        61, 74, 64, 90, 41, 78, 79, 11, 90, 32, 81, 78, 79, 72, 65, 85,  9, 90,
        75, 66, 90, 74, 81, 73, 62, 65, 78, 90, 66, 75, 81, 78,  9, 90, 44, 78,
        69, 82, 65, 80, 90, 32, 78, 69, 82, 65,  9, 90, 83, 65, 78, 65, 90, 76,
        78, 75, 81, 64, 90, 80, 75, 90, 79, 61, 85, 90, 80, 68, 61, 80, 90, 80,
        68, 65, 85, 90, 83, 65, 78, 65, 90, 76, 65, 78, 66, 65, 63, 80, 72, 85,
        90, 74, 75, 78, 73, 61, 72,  9, 90, 80, 68, 61, 74, 71, 90, 85, 75, 81,
        90, 82, 65, 78, 85, 90, 73, 81, 63, 68, 11, 90, 48, 68, 65, 85, 90, 83,
        65, 78, 65, 90, 80, 68, 65, 90, 

In [ ]:
# Splitting data into train and test sets
n = int(0.9*len(data)) # first 90% of the data will be used for training
train_data = data[:n]
val_data = data[n:]

In [ ]:
train_data

tensor([36, 61, 78,  ..., 64, 75, 75])

In [ ]:
block_size = 8
train_data[:block_size + 1]

tensor([36, 61, 78, 78, 85, 90, 44, 75, 80])

In [ ]:
x = train_data[:block_size] # input to the transformer
y = train_data[1:block_size+1] # targets for each position -> next block size characters offset by 1

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([36]) the target: 61
when input is tensor([36, 61]) the target: 78
when input is tensor([36, 61, 78]) the target: 78
when input is tensor([36, 61, 78, 78]) the target: 85
when input is tensor([36, 61, 78, 78, 85]) the target: 90
when input is tensor([36, 61, 78, 78, 85, 90]) the target: 44
when input is tensor([36, 61, 78, 78, 85, 90, 44]) the target: 75
when input is tensor([36, 61, 78, 78, 85, 90, 44, 75]) the target: 80


These have multiple examples packed into them because all these characters follow each other. When we plug any chunk of data into the transformer, we simultaneously train it to make predictions at every one of these characters individually. In a chunk of 10 characters there are 9 individual characters packed in there. In simple words, in the context of [31], 51 follows. In the context of [31, 51], 68 likely comes next.


In [ ]:
# torch.manual_seed(1332)
batch_size = 4 # no.of Independent sequences processed in parallel
block_size = 8 # what is the maximum context length for predictions

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('Inputs: ')
print(xb.shape)
print(xb)

print('Targets: ')
print(yb.shape)
print(yb)

print("-------------------")
# batch dimension
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b,:t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} the target: {target}")


Inputs: 
torch.Size([4, 8])
tensor([[74, 69, 79, 68, 90, 80, 68, 69],
        [90, 79, 81, 74, 79, 65, 80,  9],
        [75, 74, 67, 90, 80, 68, 65, 90],
        [90, 10, 90,  5, 91, 90, 90, 90]])
Targets: 
torch.Size([4, 8])
tensor([[69, 79, 68, 90, 80, 68, 69, 79],
        [79, 81, 74, 79, 65, 80,  9, 90],
        [74, 67, 90, 80, 68, 65, 90, 79],
        [10, 90,  5, 91, 90, 90, 90, 90]])
-------------------
when input is [74] the target: 69
when input is [74, 69] the target: 79
when input is [74, 69, 79] the target: 68
when input is [74, 69, 79, 68] the target: 90
when input is [74, 69, 79, 68, 90] the target: 80
when input is [74, 69, 79, 68, 90, 80] the target: 68
when input is [74, 69, 79, 68, 90, 80, 68] the target: 69
when input is [74, 69, 79, 68, 90, 80, 68, 69] the target: 79
when input is [90] the target: 79
when input is [90, 79] the target: 81
when input is [90, 79, 81] the target: 74
when input is [90, 79, 81, 74] the target: 79
when input is [90, 79, 81, 74, 79] the ta

# 1st Iteration -- Implementing a simple model

**Bigram Model**

This is a simple model that I am trying to implement. It is a simple model because the tokens are not talking to each other here. Here the predictions are made based on the last character in the sequence.

In [ ]:
# Implementing Bigram Language Model
import torch
import torch.nn as nn
from torch.nn import functional as F

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets = None):
        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (Batch = 4,Time = 8, Channels = vocab_size = 78)
        # logits are the scores for the next sequence
        # we are predictimg what comes next based on Individual indentity of a single token

        # a good way to measure the quality of predictions is to use to negative log likelihood - cross entropy
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) # measures the quality of predictions/logits wrt targets
        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B,T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # only focus on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim = -1) # (B,C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples = 1) # (B,1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim = 1) # (B, T+1)
        return idx

In [ ]:
m = BigramLanguageModel(vocab_size)
logits, loss =  m(xb,yb)
print(logits.shape)
print(loss)
idx = torch.zeros((1,1), dtype = torch.long)
print(decode(m.generate(idx, max_new_tokens = 100)[0].tolist()))

torch.Size([32, 137])
tensor(5.6301, grad_fn=<NllLossBackward0>)
!h<unk>H 9/<unk>m]<unk>p<unk>75<unk>s<unk><unk>5<unk>'
!J6[.:V,4Lg(*<unk>Lnq<unk>4<unk><unk>w<unk><unk>,<unk><unk>H1<unk><unk>G_l<1<unk>B<unk>`E3Gl<unk>J6lVB-2I<unk>P<unk>J$w<unk>rs8r\6<unk>-8<unk>r9DQ|<unk>,^


The result is utter garbage and that is because it is totally random model which we haven't even trained


In [ ]:
# Creating a Pytorch Optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr = 1e-3)

In [ ]:
batch_size = 32
for steps in range(100000):
    # sample a batch of data
    xb, yb = get_batch('train')
    # evaluate loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none = True)
    loss.backward()
    optimizer.step()
print(loss.item())

2.600524663925171


In [ ]:
print(decode(m.generate(torch.zeros((1,1), dtype = torch.long), max_new_tokens = 300)[0].tolist()))

!"I teand w ry s arr lelinipuleledorere quryoun f aus he Orrithere  Loutor lecinarermestiny an therind a a thacarongumeblins ashilly!'mary hoond.
<unk>Re w h tt Dit w- med "OUm, orctoisad ngid me o Drisththemsederot s ho att. Ched feclureveinlico ndellstimof t ad ubey t s, ithitaly scoy bly ary's be of b


# Implementing Self Attention model


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel
block_size = 32 # what is the maximum context length for predictions
max_iters = 90
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0

In [ ]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [ ]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


In [ ]:
model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

0.219017 M parameters
step 0: train loss 5.0546, val loss 5.0612
step 89: train loss 2.7420, val loss 2.7285
!atst wels as M sis fafat sope tede<unk>hice hedesadoad twangolasag hedoth nd heowlleot saerortomirmi'hig'seuun e d Rer goure wore Te wansfins'to g vont
<unk> aoriwrrire yaHr s y se ha'rard hoTk sto<unk>aste M
ind s t toe I pe 
g badre s w-nt"he ase T " Ge.leWo rkeveton Iond witlryenn
i bf   waPar<unk>, serel<unk>'b al an'ucnerede <e be snaninmenind. toith<unk> s t<unk>eing wadihy mykhaneyd t s t tstOye wanPhem?eey mhe amov me y hadwu lelrel ton Hc. g s itema' 'en'feranhiserro wtwg fBe<unk>Rove,& fitf ad toborly omenevealeo wida lenT dl cnn_ nen.
 tyoutrory .sowe nd , beRloHo <unk>hy. hac'tQra lreit nduonun cast, Oed p's
,r bund on, p wapaobrourpps fotedy sutkin whea ant
otoon hainso bere ge<unk>i}ifoyrned dswt bmude ave wo<unk>ll'inf,' wesle s. bacu <unk>d gud bo <unk> e w!aced fkerrrIisos aree  jrasangecine me iton
  to'p., n'rowo hd sfont nvede hyeediHt bsthalzs's 
We f he le